import './style.css'
import './interactive.css'
import './auth.css'
import './map-live.css'
import './profile.css'

type Tone = 'good' | 'watch' | 'high'
type View = 'overview' | 'regions' | 'timeline' | 'briefing' | 'account'
type MapLayer = 'confidence' | 'risk' | 'radar'
type Region = { name: string; confidence: number; risk: number; tone: Tone; reason: string; detail: string; signal: string }

const regions: Region[] = [
  { name: 'West Coast', confidence: 82, risk: 8, tone: 'good', reason: 'Stable synoptic pattern', detail: 'Ensemble spread remains tight and the Arabian Sea moisture plume is weakening.', signal: 'Low error signal' },
  { name: 'Central India', confidence: 64, risk: 22, tone: 'watch', reason: 'Monsoon trough displacement', detail: 'The trough is expected to shift north by 150 km, increasing rainfall timing uncertainty.', signal: 'Monitor rainfall timing' },
  { name: 'East & NE', confidence: 38, risk: 61, tone: 'high', reason: 'Depression intensification', detail: 'Rapid deepening in the Bay of Bengal is producing a wide ensemble rainfall spread.', signal: 'Priority review' },
  { name: 'North India', confidence: 71, risk: 16, tone: 'watch', reason: 'Upper-air ridge interaction', detail: 'A weak ridge is limiting confidence in thunderstorm initiation over the foothills.', signal: 'Moderate spread' },
  { name: 'Peninsular', confidence: 76, risk: 12, tone: 'good', reason: 'Consistent model agreement', detail: 'Recent hindcast analogues show low error for this moisture and wind regime.', signal: 'Low error signal' },
]
const leadData = [
  { day: 'D1', date: '22 SEP', value: 81, label: 'HIGH' }, { day: 'D2', date: '23 SEP', value: 74, label: 'HIGH' }, { day: 'D3', date: '24 SEP', value: 66, label: 'MEDIUM' }, { day: 'D4', date: '25 SEP', value: 57, label: 'MEDIUM' }, { day: 'D5', date: '26 SEP', value: 49, label: 'LOW' }, { day: 'D6', date: '27 SEP', value: 44, label: 'LOW' }, { day: 'D7', date: '28 SEP', value: 41, label: 'LOW' },
]

let activeView: View = 'overview'
let activeDay = 2
let activeRegion = 2
let mapMode: MapLayer = 'confidence'
let refreshing = false
let isAuthenticated = false
const app = document.querySelector<HTMLDivElement>('#app')!

function loginMarkup() { return `<div class="auth-shell"><div class="auth-panel"><div class="auth-brand"><div class="brand-mark"><span></span><span></span><span></span></div><div><strong>MONSOON<span>IQ</span></strong><small>FORECAST INTELLIGENCE</small></div></div><div class="auth-kicker">SECURE OPERATIONS CONSOLE</div><h1>Welcome back.</h1><p class="auth-intro">Sign in to monitor forecast confidence, bust probability, and regional risk signals.</p><form class="auth-card" id="login-form"><label>WORK EMAIL<input id="login-email" type="email" value="operator@monsooniq.in" autocomplete="username" required></label><label>PASSWORD<div class="password-field"><input id="login-password" type="password" value="Monsoon@2026" autocomplete="current-password" required><button type="button" id="toggle-password">SHOW</button></div></label><p class="auth-error" id="login-error"></p><button class="auth-submit" type="submit">Sign in to MonsoonIQ <span>→</span></button></form><div class="demo-access"><b>DEMO ACCESS</b><span>operator@monsooniq.in</span><span>Monsoon@2026</span></div><small class="auth-footer">IMD-GFS + ECMWF · Internal hindcast archive</small></div><div class="auth-visual"><div class="visual-grid"></div><div class="visual-copy"><span>MONSOON 2026</span><strong>Know where<br>forecasts may fail.</strong><p>Confidence intelligence for rapidly evolving weather systems across India.</p></div><div class="visual-stat"><b>58</b><span>OVERALL CONFIDENCE</span></div></div></div>` }

function mapMarkup() { return `<svg class="india-map" viewBox="0 0 310 365" role="img" aria-label="Forecast confidence map of India"><path class="map-outline" d="M115 18 150 31 169 62 205 78 218 111 251 135 244 159 271 184 249 209 232 231 215 268 190 282 174 326 149 347 133 318 110 305 105 273 85 256 77 221 54 202 63 172 48 145 72 121 77 89 98 68Z"/><path class="map-zone west" d="m84 72 32-18 26 42-17 66-32 24-29-28 15-38Z"/><path class="map-zone central" d="m116 98 42-8 29 36-15 55-52 20-28-17 13-47Z"/><path class="map-zone east" d="m158 91 48 18 27 29-10 40-39 9-29-37Z"/><path class="map-zone north" d="m92 39 57-8 31 35-23 28-41 7-35-27Z"/><path class="map-zone south" d="m93 202 57-21 48 20-19 66-30 60-25-40-34-18-11-38Z"/><path class="map-rain" d="M185 73c20 18 31 37 33 60"/><circle class="map-pulse" cx="190" cy="137" r="9"/><circle class="map-dot" cx="190" cy="137" r="3"/><text x="171" y="126" class="map-label">DEP.</text><text x="91" y="144" class="zone-label">WEST</text><text x="130" y="142" class="zone-label">CENTRAL</text><text x="177" y="158" class="zone-label">EAST</text></svg>` }
function header() { return `<header class="topbar"><a class="brand" href="#overview" data-view="overview"><div class="brand-mark"><span></span><span></span><span></span></div><div><strong>MONSOON<span>IQ</span></strong><small>FORECAST INTELLIGENCE</small></div></a><div class="top-actions"><div class="last-updated"><i></i><span>LIVE FEED <b>06:00 UTC</b></span></div><button class="icon-button" id="settings" aria-label="Open settings">⚙</button><button class="user-button" id="account">AK <span>▾</span></button></div></header>` }
function nav() { return `<nav class="view-nav" aria-label="Dashboard views">${([['overview', 'Overview'], ['regions', 'Regions'], ['timeline', 'Timeline'], ['briefing', 'Briefing']] as [View, string][]).map(([id, label]) => `<button class="nav-item ${activeView === id ? 'active' : ''}" data-view="${id}"><span>${id === 'overview' ? '◈' : id === 'regions' ? '▦' : id === 'timeline' ? '↗' : '▤'}</span>${label}</button>`).join('')}</nav>` }
function pageHeading(title = 'Forecast confidence monitor', subtitle = 'Decision support for where medium-range forecasts may fail.') { return `<section class="page-heading"><div><div class="eyebrow">OPERATIONAL VIEW <span class="live-dot"></span> LIVE</div><h1>${title}</h1><p>${subtitle}</p></div><div class="heading-tools"><button class="outline-button" id="refresh">${refreshing ? '✓ &nbsp; Analysis refreshed' : '↻ &nbsp; Refresh analysis'}</button><button class="primary-button" id="export">Export briefing <span>↓</span></button></div></section>` }
function statusStrip() { return `<section class="status-strip"><div class="status-main"><span class="status-icon">!</span><div><strong>Elevated uncertainty detected</strong><span>Bay of Bengal depression is intensifying faster than recent model guidance.</span></div></div><div class="status-meta"><span>THREAT LEVEL</span><b class="threat">MODERATE</b><span class="status-divider"></span><span>VALID THROUGH</span><b>26 SEP, 12Z</b></div></section>` }
function sectionHeader(kicker: string, title: string, right = '') { return `<div class="section-header"><div><div class="section-kicker">${kicker}</div><h2>${title}</h2></div>${right}</div>` }
function mapCard(selected: Region) { const riskMode = mapMode === 'risk'; const radarMode = mapMode === 'radar'; const layerTitle = radarMode ? 'LIVE PRECIPITATION RADAR' : riskMode ? 'BUST PROBABILITY MAP' : 'CONFIDENCE MAP'; const layerSub = radarMode ? 'Animated precipitation signal · Bay of Bengal system' : riskMode ? 'Probability of large forecast error · ' : 'NWP error likelihood · '; return `<div class="map-card"><div class="map-topline"><div><span class="map-title"><i class="live-map-dot"></i>${layerTitle}</span><span class="map-sub">${layerSub}${radarMode ? 'LIVE' : '22 SEP 2026, 12Z'}</span></div><div class="map-view-toggle"><button class="${!riskMode && !radarMode ? 'active' : ''}" data-map-mode="confidence">Confidence</button><button class="${riskMode ? 'active' : ''}" data-map-mode="risk">Bust risk</button><button class="${radarMode ? 'active' : ''}" data-map-mode="radar">Radar</button></div></div><div class="map-content"><div class="map-visual ${riskMode ? 'risk-mode' : ''} ${radarMode ? 'radar-mode' : ''}">${mapMarkup()}${radarMode ? '<div class="radar-sweep"></div><span class="radar-label">LIVE PRECIPITATION</span>' : ''}<div class="map-scale"><span>LOW</span><div><i></i><i></i><i></i><i></i><i></i></div><span>HIGH</span></div><div class="map-live-status"><i></i> LIVE · UPDATED 18 SEC AGO</div></div><div class="map-readout"><div class="readout-label">SELECTED REGION</div><h3>${selected.name}</h3><div class="big-score ${selected.tone}">${radarMode ? 'LIVE' : riskMode ? selected.risk : selected.confidence}<small>${radarMode ? ' signal' : riskMode ? '/100 risk' : '/100'}</small></div><div class="score-label">${radarMode ? 'PRECIPITATION ACTIVITY' : riskMode ? 'BUST PROBABILITY' : 'FORECAST CONFIDENCE'}</div><div class="readout-divider"></div><div class="readout-row"><span>Forecast confidence</span><b>${selected.confidence}%</b></div><div class="readout-row"><span>Lead time</span><b>Day ${activeDay + 1}</b></div><div class="readout-reason"><span class="reason-icon">↗</span><div><b>${radarMode ? 'Bay of Bengal system tracking live' : selected.reason}</b><p>${radarMode ? 'Precipitation cells are moving northwest toward the East & NE domain.' : selected.detail}</p></div></div></div></div><div class="map-foot"><span><i class="location-dot"></i> India domain · 0.25° resolution</span><span>Live model cycle · 06:00 UTC</span></div></div>` }
function leadCard() { return `<div class="lead-card">${leadData.map((item, index) => `<button class="lead-cell ${index === activeDay ? 'selected' : ''}" data-day="${index}"><span class="lead-day">${item.day}</span><span class="lead-date">${item.date}</span><div class="confidence-bar"><i style="height: ${item.value}%"></i></div><strong>${item.value}%</strong><em class="${item.value > 70 ? 'high' : item.value > 50 ? 'medium' : 'low'}">${item.label}</em></button>`).join('')}</div>` }
function regionList() { return `<div class="region-list">${regions.map((region, index) => `<button class="region-row ${index === activeRegion ? 'selected' : ''}" data-region="${index}"><span class="region-name"><i class="legend-dot ${region.tone}"></i>${region.name}</span><span class="mini-meter"><i style="width: ${region.confidence}%"></i></span><b>${region.confidence}%</b><span class="risk-pill ${region.tone}">${region.risk}% risk</span><span class="row-arrow">→</span></button>`).join('')}</div>` }
function explanationCard() { return `<div class="side-card explanations"><div class="card-heading"><div><div class="section-kicker">EXPLAINABLE OUTPUT</div><h2>Why confidence is low</h2></div><button class="more-button" aria-label="More explanation options">•••</button></div>${[['Rapid pressure fall', 'Surface pressure is falling at 3.2 hPa/3h near the depression core.', 'HIGH IMPACT', 'high'], ['Model disagreement', 'Rainfall accumulation spread exceeds 45 mm across 6 ensemble members.', 'MEDIUM IMPACT', 'medium'], ['Historical analogue match', 'Only 2 of 12 similar September systems had a stable track after Day 3.', 'MEDIUM IMPACT', 'medium']].map(([title, body, impact, tone], index) => `<div class="explanation-item"><span class="explain-number">0${index + 1}</span><div><b>${title}</b><p>${body}</p><span class="impact ${tone}">${impact}</span></div></div>`).join('')}<button class="full-button" data-view="briefing">View full explanation <span>→</span></button></div>` }
function summaryCard() { return `<div class="side-card summary-card"><div class="card-heading"><div><div class="section-kicker">SYSTEM SUMMARY</div><h2>Today's signal</h2></div><span class="sparkline">⌁</span></div><div class="summary-score"><div><strong>58</strong><span>/100</span></div><p>OVERALL CONFIDENCE<br><b class="down">↓ 7 pts</b> since yesterday</p></div><div class="summary-bars"><div><span>Forecast agreement</span><b>64%</b><i><em style="width:64%"></em></i></div><div><span>Historical error match</span><b>71%</b><i><em style="width:71%"></em></i></div><div><span>Event volatility</span><b class="orange-text">HIGH</b><i><em class="orange" style="width:79%"></em></i></div></div></div>` }
function briefingCard() { return `<div class="side-card brief-card"><div class="brief-icon">⌁</div><div><div class="section-kicker">OPERATIONAL BRIEF</div><h3>Plan for a wider rainfall envelope in East & NE India after Day 2.</h3><p>Next model cycle expected at 12:00 UTC.</p></div></div>` }
function overview() { const selected = regions[activeRegion]; return `${pageHeading()}${statusStrip()}<section class="dashboard-grid"><div class="main-column">${sectionHeader('REGIONAL SIGNAL', 'Where could the forecast bust?', '<div class="legend"><span><i class="legend-dot good"></i>High confidence</span><span><i class="legend-dot watch"></i>Watch</span><span><i class="legend-dot high"></i>High risk</span></div>')}${mapCard(selected)}${sectionHeader('TIME HORIZON', 'Confidence by lead time', '<span class="small-note">Model blend: IMD-GFS + ECMWF · 12Z cycle</span>')}${leadCard()}${sectionHeader('REGIONAL BREAKDOWN', 'Confidence snapshot', '<button class="text-button" data-view="regions">View all regions <span>→</span></button>')}${regionList()}</div><aside class="side-column">${summaryCard()}${explanationCard()}${briefingCard()}</aside></section>` }
function regionsView() { return `${pageHeading('Regional intelligence', 'Compare confidence, bust probability, and the meteorological driver behind each signal.')}<section class="status-strip compact-strip"><div class="status-main"><span class="status-icon">!</span><div><strong>One priority region requires review</strong><span>East & NE India is the current high-risk area for rainfall and track error.</span></div></div><b class="threat">61% BUST RISK</b></section>${sectionHeader('REGIONAL WATCHLIST', 'Five regions across the India domain', '<span class="small-note">Updated 06:00 UTC</span>')}<div class="region-list expanded-list">${regions.map((region, index) => `<button class="region-detail ${index === activeRegion ? 'selected' : ''}" data-region="${index}"><div class="detail-top"><span class="region-name"><i class="legend-dot ${region.tone}"></i>${region.name}</span><span class="risk-pill ${region.tone}">${region.risk}% bust risk</span></div><div class="detail-metrics"><div><span>Confidence</span><b>${region.confidence}%</b><i><em class="${region.tone}" style="width:${region.confidence}%"></em></i></div><div><span>Current signal</span><strong>${region.signal}</strong></div></div><p><b>${region.reason}.</b> ${region.detail}</p></button>`).join('')}</div>` }
function timelineView() { return `${pageHeading('Forecast timeline', 'Inspect how confidence decays across the Day 1 to Day 7 operational window.')}<div class="timeline-layout"><div><div class="timeline-hero"><div><div class="section-kicker">SELECTED HORIZON</div><strong>Day ${activeDay + 1}</strong><span>${leadData[activeDay].label} confidence · ${leadData[activeDay].date}</span></div><div class="timeline-hero-score">${leadData[activeDay].value}<small>/100</small></div></div>${sectionHeader('LEAD-TIME PROFILE', 'Confidence by forecast day')}<div class="timeline-list">${leadData.map((item, index) => `<button class="timeline-row ${index === activeDay ? 'selected' : ''}" data-day="${index}"><span class="timeline-day">${item.day}</span><span class="timeline-date">${item.date}</span><div class="timeline-track"><i class="${item.value > 70 ? 'good' : item.value > 50 ? 'watch' : 'high'}" style="width:${item.value}%"></i></div><b>${item.value}%</b><em class="${item.value > 70 ? 'high' : item.value > 50 ? 'medium' : 'low'}">${item.label}</em></button>`).join('')}</div></div><aside class="side-column">${summaryCard()}${briefingCard()}</aside></div>` }
function briefingView() { return `${pageHeading('Operational briefing', 'A concise handoff for weather-sensitive decisions and forecast-risk communication.')}<div class="briefing-grid"><article class="briefing-paper"><div class="paper-kicker">MONSOONIQ / DECISION NOTE  ·  22 SEP 2026, 06:00 UTC</div><h2>Widen the rainfall envelope for East & NE India after Day 2.</h2><p class="paper-lead">The current medium-range guidance is vulnerable to a track and intensity shift in the Bay of Bengal depression. Treat Day 3 onward as a scenario range rather than a single deterministic outcome.</p><div class="briefing-callout"><span>!</span><div><b>Priority signal</b><p>East & NE India has 38/100 confidence and a 61% probability of a large forecast error.</p></div></div><h3>Recommended actions</h3>${['Flag East & NE rainfall guidance as low confidence.', 'Review flood and reservoir triggers against a wider envelope.', 'Re-check the next NWP cycle before issuing Day 3 commitments.'].map((item, index) => `<div class="action-item"><span>0${index + 1}</span><p>${item}</p></div>`).join('')}<div class="paper-footer">Prepared from IMD-GFS, ECMWF ensemble guidance, and internal hindcast archive.</div></article><aside class="briefing-aside">${explanationCard()}<div class="side-card metadata"><div class="section-kicker">BRIEFING METADATA</div><div class="readout-row"><span>Valid through</span><b>26 SEP, 12Z</b></div><div class="readout-row"><span>Model blend</span><b>IMD-GFS + ECMWF</b></div><div class="readout-row"><span>Resolution</span><b>0.25° grid</b></div><div class="readout-row"><span>Next cycle</span><b>12:00 UTC</b></div></div></aside></div>` }
function accountView() { return `${pageHeading('User profile', 'Manage your MonsoonIQ workspace and operational preferences.')}<div class="profile-page"><div class="profile-card"><div class="account-avatar">AK</div><h2>Aarav Kumar</h2><p>Forecast Operations Analyst</p><span class="profile-status"><i></i> Account active · Last sign-in today</span><div class="account-details"><div><span>Work email</span><b>operator@monsooniq.in</b></div><div><span>Workspace</span><b>India domain</b></div><div><span>Access level</span><b>Operations</b></div></div></div><div class="side-card"><div class="section-kicker">NOTIFICATIONS</div><h2>Operational preferences</h2><label class="profile-toggle"><span><b>Forecast bust alerts</b><small>Notify when risk passes 50%.</small></span><i class="toggle-on"></i></label><label class="profile-toggle"><span><b>Model cycle updates</b><small>Receive next-cycle status updates.</small></span><i class="toggle-on"></i></label><button class="signout-button" id="signout">Sign out</button></div></div>` }

function render() {
  if (!isAuthenticated) {
    app.innerHTML = loginMarkup()
    document.querySelector<HTMLFormElement>('#login-form')?.addEventListener('submit', event => { event.preventDefault(); const email = document.querySelector<HTMLInputElement>('#login-email')?.value.trim().toLowerCase(); const password = document.querySelector<HTMLInputElement>('#login-password')?.value; const error = document.querySelector<HTMLParagraphElement>('#login-error'); if (email !== 'operator@monsooniq.in' || password !== 'Monsoon@2026') { if (error) error.textContent = 'Use the demo credentials shown below to continue.'; return } isAuthenticated = true; render() })
    document.querySelector<HTMLButtonElement>('#toggle-password')?.addEventListener('click', event => { const input = document.querySelector<HTMLInputElement>('#login-password'); const button = event.currentTarget as HTMLButtonElement; if (!input) return; input.type = input.type === 'password' ? 'text' : 'password'; button.textContent = input.type === 'password' ? 'SHOW' : 'HIDE' })
    return
  }
  const body = activeView === 'overview' ? overview() : activeView === 'regions' ? regionsView() : activeView === 'timeline' ? timelineView() : activeView === 'account' ? accountView() : briefingView()
  app.innerHTML = `<div class="shell">${header()}${nav()}<main>${body}</main><footer><span>MONSOONIQ v0.9 · PROTOTYPE</span><span>Data sources: IMD · NOAA GFS · ECMWF · Internal hindcast archive</span><span>System status <i class="status-online"></i> Operational</span></footer><div class="settings-drawer" id="settings-drawer"><div class="drawer-head"><div><div class="section-kicker">WORKSPACE</div><h2>Dashboard settings</h2></div><button class="icon-button" id="close-settings" aria-label="Close settings">×</button></div><label>Default map layer<select id="layer-select"><option>Forecast confidence</option><option>Bust probability</option></select></label><label class="switch-line">Auto-refresh model cycles <input type="checkbox" checked><i></i></label><p>Current data snapshot is simulated for prototype demonstration. Connect the forecast API to replace this feed.</p></div></div>`
  bindEvents()
}

function bindEvents() {
  document.querySelectorAll<HTMLElement>('[data-view]').forEach(button => button.addEventListener('click', event => { event.preventDefault(); activeView = (event.currentTarget as HTMLElement).dataset.view as View; render() }))
  document.querySelectorAll<HTMLButtonElement>('[data-day]').forEach(button => button.addEventListener('click', () => { activeDay = Number(button.dataset.day); render() }))
  document.querySelectorAll<HTMLButtonElement>('[data-region]').forEach(button => button.addEventListener('click', () => { activeRegion = Number(button.dataset.region); render() }))
  document.querySelectorAll<HTMLButtonElement>('[data-map-mode]').forEach(button => button.addEventListener('click', () => { mapMode = button.dataset.mapMode as MapLayer; render() }))
  document.querySelector<HTMLButtonElement>('#refresh')?.addEventListener('click', () => { refreshing = true; render(); window.setTimeout(() => { refreshing = false; render() }, 1400) })
  document.querySelector<HTMLButtonElement>('#export')?.addEventListener('click', () => { const text = `MONSOONIQ OPERATIONAL BRIEFING\n22 SEP 2026, 06:00 UTC\n\nPriority: East & NE India\nConfidence: 38/100\nBust probability: 61%\n\nPlan for a wider rainfall envelope after Day 2.`; const blob = new Blob([text], { type: 'text/plain' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = 'monsooniq-operational-briefing.txt'; link.click(); URL.revokeObjectURL(link.href) })
  const drawer = document.querySelector<HTMLDivElement>('#settings-drawer'); document.querySelector<HTMLButtonElement>('#settings')?.addEventListener('click', () => drawer?.classList.add('open')); document.querySelector<HTMLButtonElement>('#close-settings')?.addEventListener('click', () => drawer?.classList.remove('open')); document.querySelector<HTMLSelectElement>('#layer-select')?.addEventListener('change', event => { const value = (event.target as HTMLSelectElement).value; mapMode = value.startsWith('Bust') ? 'risk' : value.startsWith('Live') ? 'radar' : 'confidence'; render() })
  document.querySelector<HTMLButtonElement>('#account')?.addEventListener('click', () => { activeView = 'account'; render() }); document.querySelector<HTMLButtonElement>('#signout')?.addEventListener('click', () => { isAuthenticated = false; render() })
}

render()